#cargo-features = ["panic-immediate-abort"]

[package]
authors = ["ex-exist <qmained@gmail.com>"]
edition = "2021"
name = "blackpill"
version = "0.1.0"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heatshrink-lib = "1.0.0"

ssd1306 = { version = "0.10" , features = ["async", "graphics"]}
embedded-graphics = "0.8"

embassy-stm32 = { version = "0.6.0", features = ["defmt", "stm32f411re", "unstable-pac", "memory-x", "time-driver-any", "exti", "chrono"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb = { version = "0.6.0", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }

